// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBLayer.Models
{
    [Index("LastName", Name = "LastName")]
    [Index("PostalCode", Name = "PostalCode")]
    public class Employee
    {
        [Key]
        public int EmployeeID { get; set; }
        [Required]
        [StringLength(20)]
        public string LastName { get; set; }
        [Required]
        [StringLength(10)]
        public string FirstName { get; set; }
        [StringLength(30)]
        public string? Title { get; set; } = string.Empty;
        [StringLength(25)]
        public string? TitleOfCourtesy { get; set; } = string.Empty;
        [Column(TypeName = "datetime")]
        public DateTime BirthDate { get; set; } = DateTime.Now;
        [Column(TypeName = "datetime")]
        public DateTime HireDate { get; set; } = DateTime.Now;
        [StringLength(60)]
        public string? Address { get; set; } = string.Empty;
        [StringLength(15)]
        public string? City { get; set; } = string.Empty;
        [StringLength(15)]
        public string? Region { get; set; } = string.Empty;
        [StringLength(10)]
        public string? PostalCode { get; set; } = string.Empty;
        [StringLength(15)]
        public string? Country { get; set; } = string.Empty;
        [StringLength(24)]
        public string? HomePhone { get; set; } = string.Empty;
        [StringLength(4)]
        public string? Extension { get; set; } = string.Empty;
        [Column(TypeName = "ntext")]
        public string? Notes { get; set; } = string.Empty;
        public int? ReportsTo { get; set; }
        [StringLength(255)]
        public string? PhotoPath { get; set; } = string.Empty;

        //[ForeignKey("ReportsTo")]
        //[InverseProperty("InverseReportsToNavigation")]
        //public virtual Employees ReportsToNavigation { get; set; }
        //[InverseProperty("ReportsToNavigation")]
        //public virtual ICollection<Employees> InverseReportsToNavigation { get; set; } = new HashSet<Employees>();
        //[InverseProperty("Employee")]
        //public virtual ICollection<Orders> Orders { get; set; } = new HashSet<Orders>();
    }
}